name: Deploy web app to Azure Static Web Apps

env:
  APP_LOCATION: "./frontend"       # Location of your client code

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}

