name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # Adjust to your frontend directory

      - name: Build project
        run: npm run build
        working-directory: ./frontend  # Adjust to your frontend directory

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar.gz

      - name: Download artifact from GitHub
        uses: actions/download-artifact@v2
        with:
          name: build
          path: .

      - name: Extract build artifact
        run: |
          mkdir -p extract
          tar -xzf build.tar.gz -C extract
        shell: bash

      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: '2.29.2'

      - name: Log in to Azure CLI
        run: az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS.clientId }} -p ${{ secrets.AZURE_CREDENTIALS.clientSecret }} --tenant ${{ secrets.AZURE_CREDENTIALS.tenantId }}

      - name: Deploy to Azure Static Web App
        run: |
          az staticwebapp upload \
            --name your-static-web-app-name \
            --resource-group your-resource-group \
            --source-path ./extract \
            --token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
