name: Best pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history to get accurate short SHA

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Set initial version
        id: set_version
        run: echo "::set-output name=version::1.0"

      - name: Determine latest tag
        id: latest_tag
        run: echo "::set-output name=latest_tag::$(git describe --abbrev=0 --tags)"

      - name: Calculate next version
        id: next_version
        run: |
          # Determine the current version
          current_version=$(echo "${{ steps.set_version.outputs.version }}")

          # Increment the patch version
          IFS='.' read -ra version_parts <<< "$current_version"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          next_minor=$((minor + 1))

          # Set the next version
          next_version="${major}.${next_minor}"

          echo "::set-output name=next_version::${next_version}"

      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:${{ steps.next_version.outputs.next_version }} .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:${{ steps.next_version.outputs.next_version }}
