modem swap lcm,
netflix lcm swap,
itv, 


dagen op basis van atp:


maandag - > vrijdag 	4 werkdagen klopt wel
dinsdag -> maandag  	4 werkdagen klopt wel
woensdag -> maandag 	3 werkdagen klopt (wel)
donderdag -> maandag 	2 werkdagen klopt niet
vrijdag -> dinsdag 		2 werkdagen klopt niet
zaterdag -> woensdag  	3 werkdagen klopt (wel)
zondag -> donderdag  	4 werkdagen klopt wel

checken WST acceptatie omgeving

1203

1 welke datum weet niet

4 geen datu

3 civil date bruiken

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.


name: Best pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history to get accurate short SHA

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Extract short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build Docker image
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:latest .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:latest

      - name: Tag Docker image with short SHA
        run: docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:${{ steps.vars.outputs.short_sha }}

      - name: Push Docker image with short SHA tag
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cloud-remy:${{ steps.vars.outputs.short_sha }}
